### ISSUE TITLE
win.c:43:29: fatal error: imgGrabCursor.xpm: No such file or directory  #include "imgGrabCursor.xpm"

### ISSUE THREAD

**Issue by gnusupport** [lanceman2/quickplot#1]
```
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -fPIC -g -O2 -MT lib-win.lo -MD -MP -MF .deps/lib-win.Tpo -c -o lib-win.lo `test -f 'win.c' || echo './'`win.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -fPIC -g -O2 -MT lib-win.lo -MD -MP -MF .deps/lib-win.Tpo -c win.c  -fPIC -DPIC -o .libs/lib-win.o
win.c:43:29: fatal error: imgGrabCursor.xpm: No such file or directory
 #include "imgGrabCursor.xpm"
                             ^
compilation terminated.
make[1]: *** [Makefile:958: lib-win.lo] Error 1
make[1]: Leaving directory '/home/data1/protected/Programming/Software/quickplot'
make: *** [Makefile:563: all] Error 2

```

**Comment by lanceman2** [comment]
imgGrabCursor.xpm depends on the file  imgGrabCursor.png

GNU autotools (automake ?) should have automatically generated imgGrabCursor.xpm from imgGrabCursor.png via the ImageMagick program "convert" and a sed script like so:

convert imgGrabCursor.png imgGrabCursor.xpm
mv imgGrabCursor.xpm imgGrabCursor.xpm.in
sed -e 's/static.*\schar/static const char/g' imgGrabCursor.xpm.in > imgGrabCursor.xpm
rm imgGrabCursor.xpm.in

$ autoconf --version
autoconf (GNU Autoconf) 2.69

$ automake --version
automake (GNU automake) 1.15

That's the versions of autoconf and automake that I have.

If you have a tarball of quickplot that does not have imgGrabCursor.png in it, you have a "bad tarball".  If you're making it from github source than imgGrabCursor.xpm should have been generated as a prerequisite to making win.o (or whatever autotools calls object files) from win.c .

If you are building from github source you must include the --enable-developer option when running ./configure, like so:

    ./configure --enable-developer --prefix=/MY/PREFIX

I would guess that is the problem, but I'm just guessing without more info.  I'll likely make this easier (automated) in future quickplot versions.
