### ISSUE TITLE
Incompatible with current libsndfile1 

### ISSUE THREAD

**Issue by brentr** [lanceman2/quickplot#3]
Does not work as packaged in Debian 11 linked against libsndfile1 1.0.31-2
Does work linked against libsndfile1 1.0.28

The problem seems to be that sf_open_fd() mangles the file descriptor passed into it such that subsequent 
lseek(rd.fd, 0, SEEK_SET) fails

Workaround for now is to force read_sndfile to return 1 immediately, before calling
sf_open_fd()

**Comment by lanceman2** [comment]
There may be a little more to it.   I know that libsndfile had a bug in it that I did a "dlsym() hack" to it to fix it at run-time.  libsndfile claimed to work with pipe files, but then it called lseek on the file and you can't lseek pipe files.  I made libsndfile call a replacement lseek() function by using dlsym() to replace that function with my own that faked the seek effect.  I'm not looking at the code now.  I'll write more when I do.  I'm just going from ~10 year old memory, so don't think of this as gold.

    Sounds like your fix brakes the ability to read any sound files (via libsndfile).  I'm just guessing that my "dlsym() hack" is the culprit; it likely needs a larger seeky buffer, or revisiting that code in general.  It was dependent on how libsndfile did bad things.   And maybe the newer libsndfile got fixed and it really can read pipes now, but I doubt that.   I have found the author of libsndfile is not interested in fixing bugs in his code; hence I made the "dlsym() lseek() hack". 

I'll look into this later .....  This is just working notes for now, without even looking at code yet.

Thanks Brent.

**Comment by brentr** [comment]
I had suspected that the dlsym() evilness was there to deal with libsndfile issues. 
And, yes, I realize that I completely broke libsndfile support.
My use case isn't audio related.
Please ping me if I can help test.

**Comment by brentr** [comment]
I believe I found the issue in sndfile.  It's quite straightforward.
Please see:

https://github.com/libsndfile/libsndfile/issues/948

**Comment by brentr** [comment]
I've also submitted a patch against libsndfile-1.2.0

https://github.com/libsndfile/libsndfile/issues/949

**Comment by lanceman2** [comment]
Hello brentr,

Is there still an "Issue"?  Can this Issue be closed?

And again.  Thanks so much for the feedback.

And still (almost 1 year later)  it's not fixed for quickplot in Debian 12.   Not that I'm working and looking hard at it.

I'm thinking about a complete rewrite of quickplot.   I'm imagining quickplot is just the "frame capture" part of an oscilloscope; and the oscilloscope is a super set of the plot browser (quickplot).   And the oscilloscope (quickscope) is just a module used in a much larger software project that I've already started.   See Issue #5 for more details.

**Comment by brentr** [comment]
The issue was fixed in the libsndfile released with Debian 12.  See:
https://github.com/libsndfile/libsndfile/issues/948
Quickplot is a mature tool with few users having established workflows.
It will be very difficult to do a complete rewrite without disturbing those workflows.
Rather than a rewrite, how about creating a new, competing tool?
Let users transition if/when they like.

**Comment by lanceman2** [comment]
Okay.  Glad I asked.  I'll do as you suggest.

>>The issue was fixed ...

I'll close this Issue.

The new competing tool will be called quickscope; that is the new quickplot will be a sub-component of quickscope; and this quickplot repo will remain as a separate stable software project as it is.  There is an existing quickscope software project but I don't think anyone uses it.  I just tried to run quickscope and it will not run without an X11 server, so I can't (easily) use it on my Wayland based system.  I'm not sure when this will happen, but it should not effect you.

FYI: The current quickplot as in this repo, and in the Debian 12 package are broken on non-X11 (Wayland) systems.
